image:
  file: .gitpod.Dockerfile

tasks:
- before: export ROOT_URL=$(gp url 3000)
  init: meteor npm install --save
  command: meteor --settings settings.json
ports:
- port: 3000
  onOpen: open-preview
- port: 3001 # mongo db
  onOpen: ignore